# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0034_auto_20170816_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='relationships',
            field=models.ManyToManyField(related_name='relationships_of', through='member.Relationship', to='member.Member'),
        ),
    ]
